# Generated by Django 3.1.5 on 2021-06-19 23:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendasChedraui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mg', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=254)),
                ('formato', models.CharField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=2, null=True, verbose_name='2 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=3, null=True, verbose_name='3 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='subregion',
            field=models.IntegerField(null=True, verbose_name='Sub-Region Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='un',
            field=models.IntegerField(null=True, verbose_name='United Nations Code'),
        ),
    ]
