# Generated by Django 3.1.5 on 2021-06-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20210619_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='formato',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='nombre',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
